version: 2
updates:
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: npm
    directory: /packages/site
    schedule:
      interval: weekly
    labels:
      - dependencies
      - site
